icisleriKutuphaneWeb/icisleriKutuphaneWeb/Controllers/AdminLoginController.cs
using icisleriKutuphaneWeb.Models.Entity;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace icisleriKutuphaneWeb.Controllers
{
    public class AdminLoginController : Controller
    {
        icisleriBakanlıgıWebEntities db = new icisleriBakanlıgıWebEntities();

        // GET: AdminLogin
        public ActionResult IndexAdminLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IndexAdminLogin(TBPERSONEL p)
        {
            if (ModelState.IsValid)
            {
                var bilgiler = db.TBPERSONEL.FirstOrDefault(x => x.personelKullaniciAd == p.personelKullaniciAd &&
                    x.personelSifre == p.personelSifre);

                if (bilgiler != null)
                {
                    FormsAuthentication.SetAuthCookie(bilgiler.personelKullaniciAd, false);
                    Session["personelKullaniciAd"] = bilgiler.personelKullaniciAd.ToString();
                    Session["personelEmail"] = bilgiler.personelEmail; // E-posta adresini oturumda sakla
                    return RedirectToAction("IndexKitap", "kitap");
                }
                else
                {
                    ViewBag.HataMesaji = "Kullanıcı adı veya şifre yanlış.";
                    return View();
                }
            }

            ViewBag.HataMesaji = "Lütfen tüm alanları doldurun.";
            return View();
        }
    }
}

icisleriKutuphaneWeb/icisleriKutuphaneWeb/Views/AdminLogin/IndexAdminLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <style>
        body {
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
            overflow: hidden;
        }

        .background-image {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            object-fit: cover;
            background-position: center;
        }

        .login-box {
            position: relative;
            padding: 20px;
            background: rgba(255, 255, 255, 0.5);
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            margin-top: 15%;
        }

        .login-logo a {
            color: rgb(19, 24, 62);
        }

        .login-box .form-control {
            color: rgb(19, 24, 62);
        }

        .login-box .btn-primary {
            background-color: rgb(19, 24, 62);
            border-color: rgb(19, 24, 62);
        }

            .login-box .btn-primary:hover {
                background-color: rgb(14, 18, 46);
                border-color: rgb(14, 18, 46);
            }

        .login-box .form-control:focus {
            border-color: rgb(19, 24, 62);
            box-shadow: 0 0 0 0.2rem rgba(19, 24, 62, 0.1);
        }

        .login-box-msg {
            color: rgb(19, 24, 62);
            font-size: 1.0rem;
            font-weight: bold;
            text-align: center;
        }

        .alert-danger {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
            padding: 10px;
            margin-bottom: 15px;
            border-radius: 5px;
        }
    </style>
</head>
<body class="hold-transition login-page">
    <img src="~/weblogin/images/arkaplanAdmin.png" alt="Arka Plan" class="background-image">

    <div class="login-box">
        <div class="login-logo">
            <a href="~/AdminLTE-3.0.4/index2.html"><b>Personel </b> Giriş</a>
        </div>

        @using (Html.BeginForm("IndexAdminLogin", "AdminLogin", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="card">
                <div class="card-body login-card-body">
                    <p class="login-box-msg">DR. NAMIK GEDİK KÜTÜPHANESİ</p>

                    @if (!string.IsNullOrEmpty(ViewBag.HataMesaji))
                    {
                        <div class="alert alert-danger">
                            @ViewBag.HataMesaji
                        </div>
                    }

                    <div class="input-group mb-3">
                        <input type="text" name="personelKullaniciAd" class="form-control" placeholder="Personel Kullanıcı Adı" required>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" name="personelSifre" class="form-control" placeholder="Personel Şifre" required>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember">
                                <label for="remember">
                                    Beni Hatırla
                                </label>
                            </div>
                        </div>
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Giriş Yap</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
</body>
</html>